"""empty message

Revision ID: 4e61c250e812
Revises: ac4b7122b6f2
Create Date: 2019-04-04 03:22:12.857706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e61c250e812'
down_revision = 'ac4b7122b6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('username', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'username')
    # ### end Alembic commands ###
