"""empty message

Revision ID: e1ab0a0f9ed1
Revises: 4e61c250e812
Create Date: 2019-04-04 05:45:59.413832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ab0a0f9ed1'
down_revision = '4e61c250e812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('ID', sa.Integer(), nullable=False))
    op.drop_column('user_profiles', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('user_profiles', 'ID')
    # ### end Alembic commands ###
